### ISSUE TITLE
Codesandbox.io Can't resolve all parameters for ProductListComponent: (?).

### ISSUE THREAD

**Issue by brandonr1** [DeborahK/Angular-GettingStarted#133]
Hi, I'm still trying to troubleshoot it, but I ran into this issue when I tried importing from APM - Final. 

Just wanted to throw it out here in case you know a quick solution and being able to run in codesandbox would be great :)

Thanks for the course and example!

Stack:
Error: Can't resolve all parameters for ProductListComponent: (?).
    at syntaxError (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:528:34)

    at CompileMetadataResolver._getDependenciesMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15735:35)

    at CompileMetadataResolver._getTypeMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15570:26)

    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15055:24)

    at CompileMetadataResolver._getEntryComponentMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15883:45)

    at eval (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15864:48)

    at Array.forEach (<anonymous>)

    at CompileMetadataResolver._getEntryComponentsFromProvider (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15863:30)

    at eval (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15818:83)

    at Array.forEach (<anonymous>)

    at CompileMetadataResolver._getProvidersMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15781:19)

    at eval (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15783:23)

    at Array.forEach (<anonymous>)

    at CompileMetadataResolver._getProvidersMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15781:19)

    at eval (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15253:63)

    at Array.forEach (<anonymous>)

    at CompileMetadataResolver.getNgModuleMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15244:49)

    at CompileMetadataResolver.getNgModuleSummary (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15168:52)

    at eval (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15266:72)

    at Array.forEach (<anonymous>)

    at CompileMetadataResolver.getNgModuleMetadata (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:15244:49)

    at JitCompiler._loadModules (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:34428:87)

    at JitCompiler._compileModuleAndComponents (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:34389:36)

    at JitCompiler.compileModuleAsync (https://ibsit.csb.app/node_modules/@angular/compiler/bundles/compiler.umd.js:34283:37)

    at CompilerImpl.compileModuleAsync (https://ibsit.csb.app/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js:270:49)

    at PlatformRef.bootstrapModule (https://ibsit.csb.app/node_modules/@angular/core/bundles/core.umd.js:5590:25)

    at evaluate (https://ibsit.csb.app/src/main.ts:10:53)

    at ro (https://codesandbox.io/static/js/sandbox.1515ccfb1.js:1:192342)

    at e.value (https://codesandbox.io/static/js/sandbox.1515ccfb1.js:1:209186)

    at e.value (https://codesandbox.io/static/js/sandbox.1515ccfb1.js:1:231495)

    at e.value (https://codesandbox.io/static/js/sandbox.1515ccfb1.js:1:231115)

    at https://codesandbox.io/static/js/sandbox.1515ccfb1.js:1:271634

    at l (https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js:1:240622)

    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js:1:240375)

    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js:1:240979)

    at r (https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js:1:2405)

    at i (https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js:1:2616)

    at ZoneDelegate.invoke (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:386:30)

    at Zone.run (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:143:47)

    at eval (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:891:38)

    at ZoneDelegate.invokeTask (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:421:35)

    at Zone.runTask (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:188:51)

    at drainMicroTaskQueue (https://ibsit.csb.app/node_modules/zone.js/dist/zone.js:601:39)

**Comment by brandonr1** [comment]
Should have stated the error above was after tweaking things.

The actual error observed directly after import using:
https://github.com/DeborahK/Angular-GettingStarted/tree/master/APM-Final
is
Can't resolve all parameters for ApplicationModule: (?).

**Comment by DeborahK** [comment]
I'm not sure I understand. You are trying to run the application within another tool?

The only tool that I've confirmed works with this code is stackblitz. You can find the info on running the code in Stackblitz here: https://github.com/DeborahK/Angular-GettingStarted#stackblitz

**Comment by brandonr1** [comment]
No problem.  I didn't know about Stackblitz, I will try that out.  Codesandbox is another online IDE, I simply wanted to see if maybe using this project on the VSCode running out there would also work easy enough since I was already using it previously.  I figured anyone that is using codesandbox might find it beneficial as well.  If you only support Stackblitz that's fine, thanks!  If I get things working on codesandox.io I'll drop a note here in case it helps.

**Comment by DeborahK** [comment]
Thank you!

Closing this issue.
