### ISSUE TITLE
Npm Err! code ELIFECYCLE When Npm Install , Also when running npm start ( Ionic Angular Project )

### ISSUE THREAD

**Issue by GhaithBabay** [DeborahK/Angular-GettingStarted#155]
rror: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com     
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)    
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\Users\XXXX\Desktop\Dx Files\XXXXXX\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'chromedriver.storage.googleapis.com'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! XXXXXX@0.0.0 postinstall: `webdriver-manager update --standalone false --gecko false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the acurtrack@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

-----------------------------------------------------------------------------------------------

When Running Npm Start i Get this .

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! XXXXXX@0.0.0 start: `ng serve`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the acurtrack@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by DeborahK** [comment]
There is no Ionic in this github repo. If this question is not related to this repo, consider posting instead to Stackoverflow or to the ionic github pages.
