### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by GeneralBoomstick** [DeborahK/Angular-GettingStarted#96]
After copying the files from APM-Start to a new folder (APM), then running npm install, I get the following issue:

~~~ 
events.js:183░░░░░░⸩ ⠼ extract:minimist: sill extract create-ecdh@4.0.3
      throw er; // Unhandled 'error' event
      ^

Error: sha1-+HBX6ZWxofauaklgZkE3vFbwOdo= integrity checksum failed when using sha1: wanted sha1-+HBX6ZWxofauaklgZkE3vFbwOdo= but got sha1-SnW37Gz84WzStArX1pBACgHs084=. (12212 bytes)
    at Transform.on (/Users/USER/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183░░░░░░⸩ ⠏ extract:@angular/common: sill extract aws-sign2@0.7.0
      throw er; // Unhandled 'error' event
      ^

Error: sha1-+HBX6ZWxofauaklgZkE3vFbwOdo= integrity checksum failed when using sha1: wanted sha1-+HBX6ZWxofauaklgZkE3vFbwOdo= but got sha1-SnW37Gz84WzStArX1pBACgHs084=. (12212 bytes)
    at Transform.on (/Users/USER/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USER/.npm/_logs/2018-07-25T16_47_43_551Z-debug.log
~~~

The log file is attached.
[2018-07-25T16_47_43_551Z-debug.log](https://github.com/DeborahK/Angular-GettingStarted/files/2228785/2018-07-25T16_47_43_551Z-debug.log)

**Comment by DeborahK** [comment]
There are a list of suggestions for resolving this error here:

https://github.com/cncjs/cncjs/issues/172

Take a look and see if using one of these techniques helps.

Here is one example:

Try` npm cache verify` or `npm cache --force clean` to make sure everything is consistent.

**Comment by GeneralBoomstick** [comment]
Solved using the following the command found here: https://github.com/cncjs/cncjs/issues/172
`npm install --update-binary --no-shrinkwap`
